/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright XCENA Inc. */

#ifndef DAEMON_REGORUS_FFI_H
#define DAEMON_REGORUS_FFI_H

/* Generated by cbindgen from src/lib.rs. Edit that file, not this one. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace fsdaemon {
namespace regorus {
namespace abi {

/*
 The rego engine one caller owns. Opaque: only the functions below reach inside it.
 */
struct EngineHandle_t;

extern "C" {

EngineHandle_t *daemon_regorus_new();

void daemon_regorus_free(EngineHandle_t *handle);

/*
 Loads one policy module. Returns 0 on success, -1 on a parse error or bad argument.
 */
int daemon_regorus_add_policy(EngineHandle_t *handle, const char *name, const char *rego);

/*
 A clone of the base engine, for one evaluation to own. Null on a bad argument.
 */
EngineHandle_t *daemon_regorus_clone(const EngineHandle_t *handle);

/*
 Sets @input_json as the input and evaluates @query. Returns a malloc'd C string of the first
 expression's value as JSON (the policy decision object), or null on any error. Free it with
 daemon_regorus_free_string.
 */
char *daemon_regorus_eval(EngineHandle_t *handle, const char *input_json, const char *query);

void daemon_regorus_free_string(char *text);

}  // extern "C"

}  // namespace abi
}  // namespace regorus
}  // namespace fsdaemon

#endif  // DAEMON_REGORUS_FFI_H
